#!bin/bash
RED='\033[0;32m'
while : 
do
echo "${RED} INICIANDO ISABELA-MD AGUARDE PODE LEVAR ENTRE 10 A 30 SEGUNDOS, ESTE ARQUIVO É FEITO PARA O BOT NÃO CAIR, BASE: ALEATORY-MD, BOT: ISABELLA-MD, FEITO POR: Pedrim Freestyle, MEU NÚMERO: 5522999571025"
    node index.js
    sleep 1

done
